version: "3.9"

services:
  web:
    build: .
    container_name: recorte_web
    command: gunicorn main:app --bind 0.0.0.0:5000 --workers=3
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  worker:
    build: .
    container_name: recorte_worker
    command: celery -A celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  beat:
    build: .
    container_name: recorte_beat
    command: celery -A celery_worker.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15
    container_name: recorte_db
    environment:
      POSTGRES_DB: recorte_digital
      POSTGRES_USER: recorte_user
      POSTGRES_PASSWORD: recorte_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    container_name: recorte_redis
    command: redis-server --requirepass 8892fa8f29fbf1d77781e5371c8d27e66ddf8652aa33f4a0082a44cde91fe8d9 
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:

