services:
  - type: worker
    name: worker-recorte-digital-prod
    startCommand: celery -A celery worker --loglevel=info --concurrency=1 --queues=default
    # ✅ Note: "celery" (arquivo) não "app.celery_worker"

  - type: worker  
    name: beat-recorte-digital-prod
    startCommand: celery -A celery beat --loglevel=info
    envVars:
      - key: IS_BEAT
        value: "true"
