services:
  - type: web
    name: recorte-digital-oabrj-prod
    env: python
    buildCommand: |
      apt-get update &&       apt-get install -y wget gnupg unzip curl ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils libu2f-udev &&       curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb &&       apt install -y ./chrome.deb &&       pip install -r requirements.txt
    startCommand: gunicorn main:app
